export enum EStaticVar {
  USER_TOKEN_KEY = "__users-token__",
  LOCATION_KEY = "__location__",
  PHONE_KEY = "__phone__",
  PASS_KEY = "__pass__",
  ROUTES_LENGTH_PRODUCT_PAGE = 6,
  QUERY_SEARCH = "search",
  QUERY_MIN = "price-min",
  QUERY_MAX = "price-max",
  QUERY_TITLE = "title",
  LINK_MY_ITEMS = "/lk/my-items",
  LINK_NEW_ITEM = "/lk/new-item",
  LINK_SETTINGS = "/lk/settings",
  CITY_KEY = "__city__",
  PAGE_INFO = "info",
  // POSTS_TOKEN_KEY = "__posts-token__",
  // USER_TOKEN = "sdlkv3emsmlvi.oef3n.asoucn34asnoc.dfd.ee3r53fsaf",
  // TOKEN_KEY = "__is_user_token__",
  // PATH_CITY = `sevastopol`,
  // CITY_TITLE = "Севастополь",
  // EXIT = "Выход",
}
