export enum EStaticVar {
  // LOGIN = "Авторизация",
  // REGISTER = "Регистрация",
  USER_TOKEN_KEY = "__users-token__",
  ROUTES_LENGTH_PRODUCT_PAGE = 6,
  QUERY_SEARCH = "search",
  QUERY_MIN = "price-min",
  QUERY_MAX = "price-max",
  QUERY_TITLE = "title",
  // POSTS_TOKEN_KEY = "__posts-token__",
  // USER_TOKEN = "sdlkv3emsmlvi.oef3n.asoucn34asnoc.dfd.ee3r53fsaf",
  // TOKEN_KEY = "__is_user_token__",
  PHONE_KEY = "__phone__",
  LOCATION_KEY = "__location__",
  // PATH_CITY = `sevastopol`,
  // CITY_TITLE = "Севастополь",
  EXIT = "Выход",
}
