import { ICategoryMenu } from "src/app/shared/types/category.interface";

export class ApiData {
  static category: ICategoryMenu[] = [
    {
      id: 1,
      category: "Транспорт",
      body: [
        {
          id: 1,
          category: "Автомобили",
          body: null,
        },
        {
          id: 2,
          category: "Мотоциклы и мототехника",
          body: [
            { id: 1, category: "Вездеходы" },
            { id: 2, category: "Картинг" },
            { id: 3, category: "Квадроциклы и багги" },
            { id: 4, category: "Мопеды и скутеры" },
            { id: 5, category: "Мотоциклы" },
            { id: 6, category: "снегоходы" },
          ],
        },
        {
          id: 3,
          category: "Грузовики и спецтехника",
          body: [
            { id: 1, category: "Автобусы" },
            { id: 2, category: "Автодома" },
            { id: 3, category: "Автокраны" },
            { id: 4, category: "Бульдозеры" },
            { id: 5, category: "Грузовики" },
            { id: 6, category: "Коммунальная техника" },
            { id: 7, category: "Легкий коммерческий транспорт" },
            { id: 8, category: "Погрузчики" },
            { id: 9, category: "Прицепы" },
            { id: 10, category: "Сельхозтехника" },
            { id: 11, category: "Строительная техника" },
            { id: 12, category: "Техника для лесозаготовки" },
            { id: 13, category: "Тягачи" },
            { id: 14, category: "Экскаваторы" },
            { id: 15, category: "Другое" },
          ],
        },
        {
          id: 4,
          category: "Водный транспорт",
          body: [
            { id: 1, category: "Вёсельные лодки" },
            { id: 2, category: "Гидроциклы" },
            { id: 3, category: "Катера и яхты" },
            { id: 4, category: "Моторные лодки и моторы" },
          ],
        },
        {
          id: 5,
          category: "Запчасти и аксессуары",
          body: [
            { id: 1, category: "Запчасти" },
            { id: 2, category: "Шины, диски и колёса" },
            { id: 3, category: "Аудио- и видеотехника" },
            { id: 4, category: "Аксессуары" },
            { id: 5, category: "Тюнинг" },
            { id: 6, category: "Багажники и фаркопы" },
            { id: 7, category: "Инструменты" },
            { id: 8, category: "Прицепы" },
            { id: 9, category: "Экипировка" },
            { id: 10, category: "Масла и автохимия" },
            { id: 11, category: "Противоугонные устройства" },
            { id: 12, category: "GPS-навигаторы" },
          ],
        },
      ],
    },
    {
      id: 2,
      category: "Недвижимость",
      body: [
        {
          id: 1,
          category: "Купить жильё",
          body: [
            { id: 1, category: "Все квартиры" },
            { id: 2, category: "Вторичка" },
            { id: 3, category: "Новостройки" },
            { id: 4, category: "Дома, дачи, коттеджи" },
            { id: 5, category: "Комнаты" },
          ],
        },
        {
          id: 2,
          category: "Снять посуточно",
          body: [
            { id: 1, category: "Квартиры" },
            { id: 2, category: "Дома, дачи и коттедж" },
            { id: 3, category: "Комнаты и койко-места" },
          ],
        },
        {
          id: 3,
          category: "Снять долгосрочно",
          body: [
            { id: 1, category: "Квартиры" },
            { id: 2, category: "Дома, дачи и коттеджи" },
            { id: 3, category: "Комнаты и койко-места" },
          ],
        },
        {
          id: 4,
          category: "Коммерческая недвижимость",
          body: [
            { id: 1, category: "Купить" },
            { id: 2, category: "Снять" },
          ],
        },
        {
          id: 5,
          category: "Другие категории",
          body: [
            { id: 1, category: "Земельные участки" },
            { id: 2, category: "Гаражи и машиноместа" },
            { id: 3, category: "Зарубежная недвижимость" },
          ],
        },
      ],
    },
    {
      id: 3,
      category: "Работа",
      body: [
        {
          id: 1,
          category: "Ищу работу",
          body: [
            { id: 1, category: "IT, интернет, телеком" },
            { id: 2, category: "Автомобильный бизнес" },
            { id: 3, category: "Административная работа" },
            { id: 4, category: "Банки, инвестиции" },
            { id: 5, category: "Без опыта" },
            { id: 6, category: "Бухгалтерия, финансы" },
            { id: 7, category: "Высший менеджмент" },
            { id: 8, category: "Госслужба, НКО" },
            { id: 9, category: "Домашний персонал" },
            { id: 10, category: "ЖКХ, эксплуатация" },
            { id: 11, category: "Искусство, развлечения" },
            { id: 12, category: "Консультирование" },
            { id: 13, category: "Курьерская доставка" },
            { id: 14, category: "Маркетинг, реклама, PR" },
            { id: 15, category: "Медицина, фармацевтика" },
            { id: 16, category: "Образование, наука" },
            { id: 17, category: "Охрана, безопасность" },
            { id: 18, category: "Продажи" },
            { id: 19, category: "Производство, сырьё, с/х" },
            { id: 20, category: "Страхование" },
            { id: 21, category: "Строительство" },
            { id: 22, category: "Такси" },
            { id: 23, category: "Транспорт, логистика" },
            { id: 24, category: "Туризм, рестораны" },
            { id: 25, category: "Управление персоналом" },
            { id: 26, category: "Юриспруденция" },
            { id: 27, category: "Фитнес, салоны красоты" },
          ],
        },
        {
          id: 2,
          category: "Ищу сотрудника",
          body: [
            { id: 1, category: "IT, интернет, телеком" },
            { id: 2, category: "Автомобильный бизнес" },
            { id: 3, category: "Административная работа" },
            { id: 4, category: "Банки, инвестиции" },
            { id: 5, category: "Без опыта" },
            { id: 6, category: "Бухгалтерия, финансы" },
            { id: 7, category: "Высший менеджмент" },
            { id: 8, category: "Госслужба, НКО" },
            { id: 9, category: "Домашний персонал" },
            { id: 10, category: "ЖКХ, эксплуатация" },
            { id: 11, category: "Искусство, развлечения" },
            { id: 12, category: "Консультирование" },
            { id: 13, category: "Курьерская доставка" },
            { id: 14, category: "Маркетинг, реклама, PR" },
            { id: 15, category: "Медицина, фармацевтика" },
            { id: 16, category: "Образование, наука" },
            { id: 17, category: "Охрана, безопасность" },
            { id: 18, category: "Продажи" },
            { id: 19, category: "Производство, сырьё, с/х" },
            { id: 20, category: "Страхование" },
            { id: 21, category: "Строительство" },
            { id: 22, category: "Такси" },
            { id: 23, category: "Транспорт, логистика" },
            { id: 24, category: "Туризм, рестораны" },
            { id: 25, category: "Управление персоналом" },
            { id: 26, category: "Юриспруденция" },
            { id: 27, category: "Фитнес, салоны красоты" },
          ],
        },
      ],
    },
    {
      id: 4,
      category: "Услуги",
      body: [
        {
          id: 1,
          category: "Транспорт, перевозки",
          body: [
            { id: 1, category: "Автосервис" },
            { id: 2, category: "Аренда авто" },
            { id: 3, category: "Коммерческие перевозки" },
            { id: 4, category: "Грузчики" },
            { id: 5, category: "Переезды" },
            { id: 6, category: "Аренда спецтехники" },
          ],
        },
        {
          id: 2,
          category: "Ремонт и отделка",
          body: [
            { id: 1, category: "Cкважины, колодцы" },
            { id: 2, category: "Водоёмы и фонтаны" },
            { id: 3, category: "Дорожное строительство" },
            { id: 4, category: "Заборы, ограждения, навесы" },
            { id: 5, category: "Земляные работы" },
            { id: 6, category: "Озеленение, уход за садом и огородом" },
            { id: 7, category: "Рольставни и ворота" },
            { id: 8, category: "Другое" },
          ],
        },
        {
          id: 3,
          category: "Красота, здоровье",
          body: [
            { id: 1, category: "Маникюр, педикюр" },
            { id: 2, category: "Услуги парикмахера" },
            { id: 3, category: "Ресницы, брови" },
            { id: 4, category: "Косметология" },
            { id: 5, category: "Эпиляция" },
            { id: 6, category: "Макияж" },
            { id: 7, category: "СПА-услуги, массаж" },
            { id: 8, category: "Тату, пирсинг" },
            { id: 9, category: "Психология" },
            { id: 10, category: "Диетология" },
            { id: 11, category: "Аренда рабочего места" },
            { id: 12, category: "Другое" },
          ],
        },
        {
          id: 4,
          category: "Ремонт и обслуживание техники",
          body: [
            { id: 1, category: "Телевизоры" },
            { id: 2, category: "Мобильные устройства" },
            { id: 3, category: "Мелкая бытовая техника" },
            { id: 4, category: "Фото-, аудио-, видеотехника" },
            { id: 5, category: "Компьютерная техника" },
            { id: 6, category: "Игровые приставки" },
            { id: 7, category: "Крупная бытовая техника" },
          ],
        },
        {
          id: 5,
          category: "Компьютерная помощь",
          body: [
            { id: 1, category: "Компьютеры" },
            { id: 2, category: "Принтеры" },
            { id: 3, category: "Оборудование для майнинга" },
            { id: 4, category: "Игровые приставки" },
            { id: 5, category: "ОС и программы" },
            { id: 6, category: "Интернет и другие сети" },
          ],
        },
        {
          id: 6,
          category: "Установка техники",
          body: null,
        },
        {
          id: 7,
          category: "Оборудование, производство",
          body: [
            { id: 1, category: "Аренда оборудования" },
            { id: 2, category: "Монтаж и обслуживание оборудования" },
            { id: 3, category: "Производство, обработка" },
          ],
        },
        {
          id: 8,
          category: "Обучение, курсы",
          body: [
            { id: 1, category: "Предметы школы и ВУЗа" },
            { id: 2, category: "Иностранные языки" },
            { id: 3, category: "Детское развитие, логопеды" },
            { id: 4, category: "IT, бизнес" },
            { id: 5, category: "Дизайн, рисование" },
            { id: 6, category: "Красота, здоровье" },
            { id: 7, category: "Спорт, танцы" },
            { id: 8, category: "Вождение" },
            { id: 9, category: "Музыка, театр" },
            { id: 10, category: "Профессиональная подготовка" },
            { id: 11, category: "Другое" },
          ],
        },
        {
          id: 9,
          category: "Деловые услуги",
          body: [
            { id: 1, category: "Бухгалтерия, финансы" },
            { id: 2, category: "Консультирование" },
            { id: 3, category: "Набор и коррекция текста" },
            { id: 4, category: "Перевод" },
            { id: 5, category: "Юридические услуги" },
            { id: 6, category: "Страхование" },
          ],
        },
        {
          id: 10,
          category: "IT, интернет, телеком",
          body: [
            { id: 1, category: "Создание и продвижение сайтов" },
            { id: 2, category: "Установка и настройка ПО" },
            { id: 3, category: "Настройка интернета и сетей" },
            { id: 4, category: "Мастер на все случаи" },
          ],
        },
        {
          id: 11,
          category: "Реклама, полиграфия",
          body: [
            { id: 1, category: "Маркетинг, реклама, PR" },
            { id: 2, category: "Полиграфия, дизайн" },
          ],
        },
        {
          id: 12,
          category: "Вывоз мусора и вторсырья",
          body: null,
        },
        {
          id: 13,
          category: "Уборка",
          body: [
            { id: 1, category: "Генеральная уборка" },
            { id: 2, category: "Дезинфекция, дезинсекция" },
            { id: 3, category: "Мойка окон" },
            { id: 4, category: "Простая уборка" },
            { id: 5, category: "Уборка после ремонта" },
            { id: 6, category: "Чистка ковров" },
            { id: 7, category: "Чистка мягкой мебели" },
          ],
        },
        {
          id: 14,
          category: "Бытовые услуги",
          body: [
            { id: 1, category: "Изготовление ключей" },
            { id: 2, category: "Пошив и ремонт одежды" },
            { id: 3, category: "Ремонт часов" },
            { id: 4, category: "Химчистка, стирка" },
            { id: 5, category: "Ювелирные услуги" },
          ],
        },
        {
          id: 15,
          category: "Праздники, мероприятия",
          body: null,
        },
        {
          id: 16,
          category: "Доставка еды и продуктов",
          body: null,
        },
        {
          id: 17,
          category: "Фото- и видео-съёмка",
          body: null,
        },
        {
          id: 18,
          category: "Няни, сиделки",
          body: null,
        },
        {
          id: 19,
          category: "Уход за животными",
          body: null,
        },
        {
          id: 20,
          category: "Искусство",
          body: null,
        },
        {
          id: 21,
          category: "Охрана, безопасность",
          body: null,
        },
        {
          id: 22,
          category: "Доставка, курьеры",
          body: null,
        },
        {
          id: 23,
          category: "Другое",
          body: null,
        },
      ],
    },

    {
      id: 5,
      category: "Личные вещи",
      body: [
        {
          id: 1,
          category: "Одежда, обувь, аксессуары",
          body: [
            { id: 1, category: "Женская одежда" },
            { id: 2, category: "Женская обувь" },
            { id: 3, category: "Мужская одежда" },
            { id: 4, category: "Мужская обувь" },
            { id: 5, category: "Сумки, рюкзаки и чемоданы" },
            { id: 6, category: "Аксессуары" },
          ],
        },
        {
          id: 2,
          category: "Детская одежда и обувь",
          body: [
            { id: 1, category: "Для девочек" },
            { id: 2, category: "Для мальчиков" },
          ],
        },
        {
          id: 3,
          category: "Товары для детей и игрушки",
          body: [
            { id: 1, category: "Детские коляски" },
            { id: 2, category: "Детская мебель" },
            { id: 3, category: "Велосипеды и самокаты" },
            { id: 4, category: "Товары для кормления" },
            { id: 5, category: "Автомобильные кресла" },
            { id: 6, category: "Постельные принадлежности" },
            { id: 7, category: "Игрушки" },
            { id: 8, category: "Товары для купания" },
            { id: 9, category: "Товары для школы" },
          ],
        },
        {
          id: 4,
          category: "Красота и здоровье",
          body: [
            { id: 1, category: "Приборы и аксессуары" },
            { id: 2, category: "Парфюмерия" },
            { id: 3, category: "Средства гигиены" },
            { id: 4, category: "Косметика" },
            { id: 5, category: "Средства для волос" },
            { id: 6, category: "Медицинские изделия" },
            { id: 7, category: "Другое" },
          ],
        },
        {
          id: 5,
          category: "Часы и украшения",
          body: [
            { id: 1, category: "Ювелирные изделия" },
            { id: 2, category: "Бижутерия" },
            { id: 3, category: "Часы" },
          ],
        },
      ],
    },
    {
      id: 6,
      category: "Для дома и дачи",
      body: [
        {
          id: 1,
          category: "Ремонт и строительство",
          body: [
            { id: 1, category: "Стройматериалы" },
            { id: 2, category: "Инструменты" },
            { id: 3, category: "Сантехника, водоснабжение и сауна" },
            { id: 4, category: "Двери" },
            { id: 5, category: "Садовая техника" },
            { id: 6, category: "Окна и балконы" },
            { id: 7, category: "Камины и обогреватели" },
            { id: 8, category: "Готовые строения и срубы" },
            { id: 9, category: "Потолки" },
          ],
        },
        {
          id: 2,
          category: "Мебель и интерьер",
          body: [
            { id: 1, category: "Кровати, диваны и кресла" },
            { id: 2, category: "Шкафы, комоды и стеллажи" },
            { id: 3, category: "Столы и стулья" },
            { id: 4, category: "Текстиль и ковры" },
            { id: 5, category: "Кухонные гарнитуры" },
            { id: 6, category: "Предметы интерьера, искусство" },
            { id: 7, category: "Освещение" },
            { id: 8, category: "Компьютерные столы и кресла" },
            { id: 9, category: "Подставки и тумбы" },
            { id: 10, category: "Другое" },
          ],
        },
        {
          id: 3,
          category: "Бытовая техника",
          body: [
            { id: 1, category: "Для кухни" },
            { id: 2, category: "Для дома" },
            { id: 3, category: "Климатическое оборудование" },
            { id: 4, category: "Для индивидуального ухода" },
            { id: 5, category: "Другое" },
          ],
        },
        {
          id: 4,
          category: "Продукты питания",
          body: null,
        },
        {
          id: 5,
          category: "Растения",
          body: null,
        },
        {
          id: 6,
          category: "Посуда и товары для кухни",
          body: [
            { id: 1, category: "Посуда" },
            { id: 2, category: "Товары для кухни" },
          ],
        },
      ],
    },
    {
      id: 7,
      category: "Запчасти и аксессуары",
      body: [
        {
          id: 1,
          category: "Запчасти",
          body: [
            { id: 1, category: "Для автомобилей" },
            { id: 2, category: "Для мототехники" },
            { id: 3, category: "Для грузовиков и спецтехники" },
            { id: 4, category: "Для водного транспорта" },
          ],
        },
        {
          id: 2,
          category: "Шины, диски и колёса",
          body: [
            { id: 1, category: "Шины" },
            { id: 2, category: "Шины для грузовиков и спецтехники" },
            { id: 3, category: "Мотошины" },
            { id: 4, category: "Диски" },
            { id: 5, category: "Колпаки" },
            { id: 6, category: "Колёса" },
          ],
        },
        {
          id: 3,
          category: "Аудио- и видеотехника",
          body: null,
        },
        {
          id: 4,
          category: "Аксессуары",
          body: null,
        },
        {
          id: 5,
          category: "Тюнинг",
          body: null,
        },
        {
          id: 6,
          category: "Багажники и фаркопы",
          body: null,
        },
        {
          id: 7,
          category: "Инструменты",
          body: null,
        },
        {
          id: 8,
          category: "Прицепы",
          body: null,
        },
        {
          id: 9,
          category: "Экипировка",
          body: null,
        },
        {
          id: 10,
          category: "Масла и автохимия",
          body: null,
        },
        {
          id: 11,
          category: "Противоугонные устройства",
          body: [
            { id: 1, category: "Автосигнализации" },
            { id: 2, category: "Иммобилайзеры" },
            { id: 3, category: "Механические блокираторы" },
            { id: 4, category: "Спутниковые системы" },
          ],
        },
        {
          id: 12,
          category: "GPS-навигаторы",
          body: null,
        },
      ],
    },
    {
      id: 8,
      category: "Электроника",
      body: [
        {
          id: 1,
          category: "Телефоны",
          body: [
            { id: 1, category: "Мобильные телефоны" },
            { id: 2, category: "Аксессуары" },
            { id: 3, category: "Рации" },
            { id: 4, category: "Стационарные телефоны" },
          ],
        },
        {
          id: 2,
          category: "Аудио и видео",
          body: [
            { id: 1, category: "Телевизоры и проекторы" },
            { id: 2, category: "Наушники" },
            { id: 3, category: "Акустика, колонки, сабвуфера" },
            { id: 4, category: "Аксессуары" },
            { id: 5, category: "Музыкальные центры, магнитолы" },
            { id: 6, category: "Усилители и ресиверы" },
            { id: 7, category: "Видеокамеры" },
            { id: 8, category: "Видео, DVD и Blu-ray плееры" },
            { id: 9, category: "Кабели и адаптеры" },
            { id: 10, category: "Музыка и фильмы" },
            { id: 11, category: "Микрофоны" },
            { id: 12, category: "MP3-плееры" },
          ],
        },
        {
          id: 3,
          category: "Товары для компьютера",
          body: [
            { id: 1, category: "Комплектующие" },
            { id: 2, category: "Мониторы" },
            { id: 3, category: "Сетевое оборудование" },
            { id: 4, category: "Клавиатуры и мыши" },
            { id: 5, category: "Аксессуары" },
            { id: 6, category: "Джойстики и рули" },
            { id: 7, category: "Флэшки и карты памяти" },
            { id: 8, category: "Акустика" },
            { id: 9, category: "Переносные жёсткие диски" },
            { id: 10, category: "Веб-камеры" },
            { id: 11, category: "ТВ-тюнеры" },
          ],
        },
        {
          id: 4,
          category: "Игры, приставки и программы",
          body: [
            { id: 1, category: "Игровые приставки" },
            { id: 2, category: "Игры для приставок" },
            { id: 3, category: "Программы" },
            { id: 4, category: "Компьютерные игры" },
          ],
        },
        {
          id: 5,
          category: "Ноутбуки",
          body: null,
        },
        {
          id: 6,
          category: "Настольные компьютеры",
          body: [
            { id: 1, category: "Системные блоки" },
            { id: 2, category: "Моноблоки" },
            { id: 3, category: "Другое" },
          ],
        },
        {
          id: 7,
          category: "Фототехника",
          body: [
            { id: 1, category: "Оборудование и аксессуары" },
            { id: 2, category: "Объективы" },
            { id: 3, category: "Компактные фотоаппараты" },
            { id: 4, category: "Плёночные фотоаппараты" },
            { id: 5, category: "Зеркальные фотоаппараты" },
            { id: 6, category: "Бинокли и телескопы" },
          ],
        },
        {
          id: 8,
          category: "Планшеты и электронные книги",
          body: [
            { id: 1, category: "Планшеты" },
            { id: 2, category: "Аксессуары" },
            { id: 3, category: "Электронные книги" },
          ],
        },
        {
          id: 9,
          category: "Оргтехника и расходники",
          body: [
            { id: 1, category: "МФУ, копиры и сканеры" },
            { id: 2, category: "Принтеры" },
            { id: 3, category: "Канцелярия" },
            { id: 4, category: "ИБП, сетевые фильтры" },
            { id: 5, category: "Телефония" },
            { id: 6, category: "Уничтожители бумаг" },
            { id: 7, category: "Расходные материалы" },
          ],
        },
        {
          id: 10,
          category: "Масла и автохимия",
          body: null,
        },
        {
          id: 11,
          category: "Противоугонные устройства",
          body: [
            { id: 1, category: "Автосигнализации" },
            { id: 2, category: "Иммобилайзеры" },
            { id: 3, category: "Механические блокираторы" },
            { id: 4, category: "Спутниковые системы" },
          ],
        },
        {
          id: 12,
          category: "GPS-навигаторы",
          body: null,
        },
      ],
    },
    {
      id: 9,
      category: "Хобби и отдых",
      body: [
        {
          id: 1,
          category: "Билеты и путешествия",
          body: [
            { id: 1, category: "Карты, купоны" },
            { id: 2, category: "Концерты" },
            { id: 3, category: "Путешествия" },
            { id: 4, category: "Спорт" },
            { id: 5, category: "Театр, опера, балет" },
            { id: 6, category: "Цирк, кино" },
            { id: 7, category: "Шоу, мюзикл" },
          ],
        },
        {
          id: 2,
          category: "Велосипеды",
          body: [
            { id: 1, category: "Горные" },
            { id: 2, category: "Дорожные" },
            { id: 3, category: "ВМХ" },
            { id: 4, category: "Детские" },
            { id: 5, category: "Запчасти и аксессуары" },
          ],
        },
        {
          id: 3,
          category: "Книги и журналы",
          body: [
            { id: 1, category: "Журналы, газеты, брошюры" },
            { id: 2, category: "Книги" },
            { id: 3, category: "Учебная литература" },
          ],
        },
        {
          id: 4,
          category: "Коллекционирование",
          body: [
            { id: 1, category: "Банкноты" },
            { id: 2, category: "Билеты" },
            { id: 3, category: "Вещи знаменитостей, автографы" },
            { id: 4, category: "Военные вещи" },
            { id: 5, category: "Грампластинки" },
            { id: 6, category: "Документы" },
            { id: 7, category: "Жетоны, медали, значки" },
            { id: 8, category: "Игры" },
            { id: 9, category: "Календари" },
            { id: 10, category: "Картины" },
            { id: 11, category: "Киндер-сюрприз" },
            { id: 12, category: "Конверты и почтовые карточки" },
            { id: 13, category: "Марки" },
            { id: 14, category: "Модели" },
            { id: 15, category: "Монеты" },
            { id: 16, category: "Открытки" },
            { id: 17, category: "Пепельницы, зажигалки" },
            { id: 18, category: "Пластиковые карточки" },
            { id: 19, category: "Спортивные карточки" },
            { id: 20, category: "Фотографии, письма" },
            { id: 21, category: "Этикетки, бутылки, пробки" },
            { id: 22, category: "Другое" },
          ],
        },
        {
          id: 5,
          category: "Музыкальные инструменты",
          body: [
            { id: 1, category: "Аккордеоны, гармони, баяны" },
            { id: 2, category: "Гитары и другие струнные" },
            { id: 3, category: "Духовые" },
            { id: 4, category: "Пианино и другие клавишные" },
            { id: 5, category: "Скрипки и другие смычковые" },
            { id: 6, category: "Ударные" },
            { id: 7, category: "Для студии и концертов" },
            { id: 8, category: "Аксессуары" },
          ],
        },
        {
          id: 6,
          category: "Охота и рыбалка",
          body: null,
        },
        {
          id: 7,
          category: "Спорт и отдых",
          body: [
            { id: 1, category: "Бильярд и боулинг" },
            { id: 2, category: "Дайвинг и водный спорт" },
            { id: 3, category: "Единоборства" },
            { id: 4, category: "Зимние виды спорта" },
            { id: 5, category: "Игры с мячом" },
            { id: 6, category: "Настольные игры" },
            { id: 7, category: "Пейнтбол и страйкбол" },
            { id: 8, category: "Ролики и скейтбординг" },
            { id: 9, category: "Теннис, бадминтон, пинг-понг" },
            { id: 10, category: "Туризм" },
            { id: 11, category: "Фитнес и тренажёры" },
            { id: 12, category: "Другое" },
          ],
        },
        {
          id: 8,
          category: "Планшеты и электронные книги",
          body: [
            { id: 1, category: "Планшеты" },
            { id: 2, category: "Аксессуары" },
            { id: 3, category: "Электронные книги" },
          ],
        },
        {
          id: 9,
          category: "Оргтехника и расходники",
          body: [
            { id: 1, category: "МФУ, копиры и сканеры" },
            { id: 2, category: "Принтеры" },
            { id: 3, category: "Канцелярия" },
            { id: 4, category: "ИБП, сетевые фильтры" },
            { id: 5, category: "Телефония" },
            { id: 6, category: "Уничтожители бумаг" },
            { id: 7, category: "Расходные материалы" },
          ],
        },
        {
          id: 10,
          category: "Масла и автохимия",
          body: null,
        },
        {
          id: 11,
          category: "Противоугонные устройства",
          body: [
            { id: 1, category: "Автосигнализации" },
            { id: 2, category: "Иммобилайзеры" },
            { id: 3, category: "Механические блокираторы" },
            { id: 4, category: "Спутниковые системы" },
          ],
        },
        {
          id: 12,
          category: "GPS-навигаторы",
          body: null,
        },
      ],
    },
    {
      id: 10,
      category: "Животные",
      body: [
        {
          id: 1,
          category: "Собаки",
          body: null,
        },
        {
          id: 2,
          category: "Кошки",
          body: null,
        },
        {
          id: 3,
          category: "Птицы",
          body: null,
        },
        {
          id: 4,
          category: "Аквариум",
          body: null,
        },
        {
          id: 5,
          category: "Другие животные",
          body: [
            { id: 1, category: "Амфибии" },
            { id: 2, category: "Грызуны" },
            { id: 3, category: "Кролики" },
            { id: 4, category: "Лошади" },
            { id: 5, category: "Рептилии" },
            { id: 6, category: "С/х животные" },
            { id: 7, category: "Хорьки" },
            { id: 8, category: "Другое" },
          ],
        },
        {
          id: 6,
          category: "Товары для животных",
          body: null,
        },
      ],
    },
    {
      id: 11,
      category: "Бизнес и оборудование",
      body: [
        {
          id: 1,
          category: "СоГотовый бизнес",
          body: [
            { id: 1, category: "Интернет-магазины и IT" },
            { id: 2, category: "Общественное питание" },
            { id: 3, category: "Производство" },
            { id: 4, category: "Развлечения" },
            { id: 5, category: "Сельское хозяйство" },
            { id: 6, category: "Строительство" },
            { id: 7, category: "Сфера услуг" },
            { id: 8, category: "Магазины и пункты выдачи заказов" },
            { id: 9, category: "Автобизнес" },
            { id: 10, category: "Красота и уход" },
            { id: 11, category: "Стоматология и медицина" },
            { id: 12, category: "Туризм" },
            { id: 13, category: "Другое" },
          ],
        },
        {
          id: 2,
          category: "Оборудование для бизнеса",
          body: [
            { id: 1, category: "Промышленное" },
            { id: 2, category: "Логистика и склад" },
            { id: 3, category: "Для магазина" },
            { id: 4, category: "Для ресторана" },
            { id: 5, category: "Для салона красоты" },
            { id: 6, category: "Для автобизнеса" },
            { id: 7, category: "Расчётно-кассовое" },
            { id: 8, category: "Рекламное" },
            { id: 9, category: "Развлекательное" },
            { id: 10, category: "Ресепшены и офисная мебель" },
            { id: 11, category: "Майнинг" },
            { id: 12, category: "Киоски и передвижные сооружения" },
            { id: 13, category: "Лабораторное" },
            { id: 14, category: "Медицинское" },
            { id: 15, category: "Телекоммуникационное" },
            { id: 16, category: "Другое" },
          ],
        },
      ],
    },
  ];
}
